### ISSUE TITLE
Not working for restrict screen mirroring

### ISSUE THREAD

**Issue by Trusharbhatt** [adaptant-labs/flutter_windowmanager#1]
We have tried it as given example and  testing with multiple scenario it is working while app in stack means screen is secure while app goes to background  but  with screen mirroring it not working so is there any way to **restrict **screen mirroring and video recording**** by other app ?

Thank you in advance.

**Comment by pmundt** [comment]
This would seem like a general issue with screen mirroring, and one that there does not seem to be a general fix for (at least at the flag level). One solution, as per https://stackoverflow.com/questions/39886750/disable-ios-android-screen-mirroring, is to detect for the existence of multiple displays and to take action (e.g. by iterating over each display and setting FLAG_SECURE for each of the display params). Could you verify whether this would work for your case?
