### ISSUE TITLE
Have something or some package, something that works like the FLAG_KEEP_SCREEN_ON for IOS

### ISSUE THREAD

**Issue by Unterable** [adaptant-labs/flutter_windowmanager#10]
**Have something or some package, something that works like the FLAG_KEEP_SCREEN_ON for IOS ?
it's just a doubt!**

**Comment by pmundt** [comment]
It looks like someone has released the [keep_screen_on](https://pub.dev/packages/keep_screen_on) package, which should do exactly what you want for both Android and iOS.
