### ISSUE TITLE
Migrate to Android V2 embedding

### ISSUE THREAD

**Issue by hpoul** [adaptant-labs/flutter_windowmanager#17]
With the latest flutter (dev) channel the following warning is shown. I guess it would be time to migrate to the new embedding apis.
If this project is still maintained i can try to create a PR?

```
Running "flutter pub get" in authpass...                         2,069ms
The plugin `flutter_windowmanager` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding.
Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding:
https://flutter.dev/go/android-plugin-migration.
```

**Comment by pmundt** [comment]
My apologies for the late reply, somehow I missed the notification for this and just got the one on the PR. Yes, it looks like with the newer versions we now have to update the embeddings. I'll take a look through the PR and cut a new release if everything checks out!
