### ISSUE TITLE
Plugin not available  in IOS 

### ISSUE THREAD

**Issue by pragadeeshNIS** [adaptant-labs/flutter_windowmanager#2]

**Comment by pmundt** [comment]
Thanks for bringing this up - indeed, I do not have an environment where I am able to build or test for iOS. I'm happy for any PRs that can address implementation gaps to enable this, however.

**Comment by zenwong** [comment]
I was able to get it to run on iOS by changing pubspec.yaml to

`flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: io.adaptant.labs.flutter_windowmanager
        pluginClass: FlutterWindowManagerPlugin`

and also generating a dummy ios folder.  I still get 
`Unhandled Exception: MissingPluginException(No implementation found for method addFlags on channel flutter_windowmanager)`

when running on iOS tho.
>

**Comment by pmundt** [comment]
Thanks @zenwong, unfortunately there is logic in the iOS plugin that needs to wrap into the corresponding Android service, so simply adding the plugin scaffolding to the build will not be sufficient. I see that @neckaros has created a fork at https://github.com/neckaros/flutter_windowmanager that looks to have added iOS support already, but I've not received a PR for this to date. Can you see if this works for you?

**Comment by neckaros** [comment]
Hello,

My fork allow build on iOS but does not add the functionality to iOS.

If you want to also have the functionality I created a package with also in app securitization:
https://pub.dev/packages/secure_application

Hope it can help

@pmundt i will try to send à PR request if you want but know that it throw not implemented on iOS as the functionality is not available on iOS

Regards

**Comment by pmundt** [comment]
@neckaros thanks for clarifying! Indeed, I was not sure the extent to which iOS services would provide a 1:1 mapping with the Android layout params. Perhaps the better option is that I simply document that this plugin is Android-only and include a link to your `secure_application` plugin for people that require the secure window capability on iOS.

**Comment by Unterable** [comment]
@neckaros Have something or some package, something that works like the FLAG_KEEP_SCREEN_ON for IOS ?
