### ISSUE TITLE
flutter_windowmanager has been deprecated, need to update as per latest flutter version

### ISSUE THREAD

**Issue by kamleshwebtech** [adaptant-labs/flutter_windowmanager#20]
Getting below error in console panel:

```
The plugins `flutter_windowmanager` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
```

Need to update `flutter_windowmanager` plugin as per latest flutter version. Thanks.

**Comment by pmundt** [comment]
The embedding was updated in version 0.2.0 of the plugin. Can you update the dependency version and try again?

**Comment by afandiyusuf** [comment]
@pmundt confirmed, by updating to 0.2.0, the warning is gone.
Thanks @pmundt

**Comment by adispatil** [comment]
This library records audio when playing video... tested on android 10 and 11.. I am using 0.2.0 version

**Comment by pmundt** [comment]
@adispatil I''m not sure how that would happen given that the library contains no logic beyond toggling application flags, but if you've encountered something like this, please open a separate issue with more information and steps to reproduce and I'd be happy to have a look at it.

**Comment by pmundt** [comment]
Thanks for the confirmation @afandiyusuf, I'm now closing this as resolved.

**Comment by kamleshwebtech** [comment]
Thanks a lot dear @pmundt  for making this package NULL SAFETY. Happy to add this gem in my 3 projects :)
