### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method addFlags on channel flutter_windowmanager)

### ISSUE THREAD

**Issue by priyaranjan-mantri** [adaptant-labs/flutter_windowmanager#26]
Restarted application in 10,507ms.
E/flutter (15958): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method addFlags on channel flutter_windowmanager)
E/flutter (15958): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:165
E/flutter (15958): <asynchronous suspension>
E/flutter (15958): #1      FlutterWindowManager.addFlags (package:flutter_windowmanager/flutter_windowmanager.dart:111:12)
E/flutter (15958): <asynchronous suspension>
E/flutter (15958): #2      main
package:myproject/main.dart:22
E/flutter (15958): <asynchronous suspension>
E/flutter (15958):

**Comment by OmarBlancko** [comment]
how did you solve it ?
