### ISSUE TITLE
FLAG_ALT_FOCUSABLE_IM

### ISSUE THREAD

**Issue by martaross** [adaptant-labs/flutter_windowmanager#4]
FLAG_ALT_FOCUSABLE_IM flag does not work with the plugin. It's intended to disable the soft keyboard, if you are using a physical one.

**Comment by pmundt** [comment]
I unfortunately do not see anything obvious as to why it wouldn't, and can at least verify that the flag is being correctly set for me. Have you tried with/without FLAG_NOT_FOCUSABLE?
