### ISSUE TITLE
i have used flag_secure flag but it is not preventing from screen recording

### ISSUE THREAD

**Issue by HetalGohil** [adaptant-labs/flutter_windowmanager#5]

**Comment by pmundt** [comment]
`FLAG_SECURE` will prevent screenshots, but recording is not blocked in all Android versions, and is also rather device-specific. I'm afraid there is no straightforward way to inhibit video capture at the moment.

**Comment by Bharavi26** [comment]
I have same issue prevent screenshot but not block video recorder
