### ISSUE TITLE
FlutterWindowManager.FLAG_SECURE

### ISSUE THREAD

**Issue by Bharavi26** [adaptant-labs/flutter_windowmanager#6]
await FlutterWindowManager.addFlags(FlutterWindowManager.FLAG_SECURE);

not able to prevent **screen video recorder** using this..(tested using DU Recorder)

**Comment by hacker1024** [comment]
Screen recorders do not respect this flag, this issue is beyond the scope of this plugin.

**Comment by pmundt** [comment]
Indeed, it's a bit counterintuitive, but as @hacker1024 has pointed out, we can't do much about this from the plugin side. It's ultimately up to the Android side to determine to what extent it will obey the flag, and screen recorders are at least one known issue.
